# Generated by Django 6.0.6 on 2026-07-19 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('nom_original', models.CharField(blank=True, max_length=255)),
                ('categorie', models.CharField(choices=[('PASSEPORT', 'Passeport'), ('NIE', 'NIE'), ('DNI', 'DNI'), ('EMPADRONAMIENTO', 'Empadronamiento'), ('CONTRAT', 'Contrat'), ('VIDA_LABORAL', 'Vida laboral'), ('FICHE_PAIE', 'Fiche de paie'), ('DIPLOME', 'Diplôme'), ('CASIER_JUDICIAIRE', 'Casier judiciaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='dossiers.dossier')),
                ('televerse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_televerses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
