# Generated by Django 6.0.6 on 2026-07-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categoria_sugerida',
            field=models.CharField(blank=True, choices=[('PASSEPORT', 'Passeport'), ('NIE', 'NIE'), ('DNI', 'DNI'), ('EMPADRONAMIENTO', 'Empadronamiento'), ('CONTRAT', 'Contrat'), ('VIDA_LABORAL', 'Vida laboral'), ('FICHE_PAIE', 'Fiche de paie'), ('DIPLOME', 'Diplôme'), ('CASIER_JUDICIAIRE', 'Casier judiciaire'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='datos_extraidos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='error_ia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='estado_ia',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('SIN_CLAVE', 'Sin clave configurada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
