# Generated by Django 6.0.6 on 2026-07-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('documents', '0002_document_categoria_sugerida_document_datos_extraidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cliente_confirmado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client'),
        ),
    ]
