# Generated by Django 6.0.6 on 2026-07-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_cliente_confirmado_alter_document_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='estado_ia',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error'), ('SIN_CLAVE', 'Sin clave configurada'), ('SIMULADO', 'Simulado (modo de prueba)')], default='PENDIENTE', max_length=20),
        ),
    ]
