# Generated by Django 6.0.6 on 2026-07-19 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('type_procedure', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('PREPARATION', 'En préparation'), ('DEPOSE', 'Déposé'), ('REQUERIMIENTO', 'Requerimiento'), ('RESOLU', 'Résolu')], default='PREPARATION', max_length=20)),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='clients.client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date_ouverture', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DossierEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, choices=[('PREPARATION', 'En préparation'), ('DEPOSE', 'Déposé'), ('REQUERIMIENTO', 'Requerimiento'), ('RESOLU', 'Résolu')], max_length=20)),
                ('nouveau_statut', models.CharField(choices=[('PREPARATION', 'En préparation'), ('DEPOSE', 'Déposé'), ('REQUERIMIENTO', 'Requerimiento'), ('RESOLU', 'Résolu')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_evenements', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Événement de dossier',
                'verbose_name_plural': 'Événements de dossier',
                'ordering': ['-created_at'],
            },
        ),
    ]
